{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-ms
  version: {{ version }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_ms
    - qiime2.plugins.ms
  commands:
    - pytest --cov q2_ms --cov-report xml:coverage.xml --pyargs q2_ms

about:
  home: https://github.com/bokulich-lab/q2-ms
  license: BSD-3-Clause
  license_family: BSD
